// <auto-generated />
using System;
using ChitCore.Data.v1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChitCore.Data.Migrations
{
    [DbContext(typeof(ChitDbContext))]
    [Migration("20180728165448_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChitCore.Data.v1.Models.AuctionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActionedDate");

                    b.Property<DateTime>("AmountDueBy");

                    b.Property<decimal>("BidAmount");

                    b.Property<int>("ChitId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChitId");

                    b.HasIndex("UserId");

                    b.ToTable("AuctionDetails");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.Chit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AuctionDate");

                    b.Property<int>("Commission");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NoOfMonths");

                    b.Property<int>("NoOfUsers");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StatusId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Chits");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.ChitAdministrator", b =>
                {
                    b.Property<int>("ChitId");

                    b.Property<int>("UserId");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ChitId", "UserId");

                    b.HasIndex("ChitId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("AK_ChitAdministrator_Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChitAdministrator");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.ChitUser", b =>
                {
                    b.Property<int>("ChitId");

                    b.Property<int>("UserId");

                    b.Property<int>("ChitUserTypeId");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ChitId", "UserId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("AK_ChitUsers_Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChitUsers");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.PaymentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountPaid");

                    b.Property<int>("ChitId");

                    b.Property<DateTime>("PaidDate");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChitId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("Minitial")
                        .HasColumnName("MInitial");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("StatusId");

                    b.Property<int>("UserTypeId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.AuctionDetail", b =>
                {
                    b.HasOne("ChitCore.Data.v1.Models.Chit", "Chit")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("ChitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChitCore.Data.v1.Models.User", "User")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.Chit", b =>
                {
                    b.HasOne("ChitCore.Data.v1.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.ChitAdministrator", b =>
                {
                    b.HasOne("ChitCore.Data.v1.Models.Chit", "Chit")
                        .WithOne("ChitAdministrator")
                        .HasForeignKey("ChitCore.Data.v1.Models.ChitAdministrator", "ChitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChitCore.Data.v1.Models.User", "User")
                        .WithMany("ChitAdministrator")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.ChitUser", b =>
                {
                    b.HasOne("ChitCore.Data.v1.Models.Chit", "Chit")
                        .WithMany("ChitUsers")
                        .HasForeignKey("ChitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChitCore.Data.v1.Models.User", "User")
                        .WithMany("ChitUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChitCore.Data.v1.Models.PaymentDetail", b =>
                {
                    b.HasOne("ChitCore.Data.v1.Models.Chit", "Chit")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("ChitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChitCore.Data.v1.Models.User", "User")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
