// <auto-generated />
using ChitCoreApi;
using ChitCoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using static ChitCoreApi.ChitCoreApiConstants;

namespace ChitCoreApi.Migrations
{
    [DbContext(typeof(ChitDbContext))]
    partial class ChitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChitCoreApi.ChitMgmt.post.v1.Models.Chit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AuctionDate");

                    b.Property<int>("Commission");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("ManagerId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NoOfMonths");

                    b.Property<int>("NoOfUsers");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StatusId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.ToTable("Chits");
                });

            modelBuilder.Entity("ChitCoreApi.ChitMgmt.post.v1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("MInitial");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreateDate").HasDefaultValue(DateTime.Now);

                    b.Property<DateTime>("LastUpdatedDate").HasDefaultValue(DateTime.Now);

                    b.Property<int>("StatusId").HasDefaultValue((int)CustomerStatus.New);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChitCoreApi.ChitMgmt.post.v1.Models.ChitUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("ChitId")
                    .IsRequired();

                b.Property<int>("UserId")
                   .IsRequired();

                b.HasKey("Id");

                b.ToTable("ChitUser");
            });
        }
    }
}
